openapi: 3.2.0
info:
  title: 'Pressable API Documentation (v1) Http: API'
  version: 1.0.0
  description: The Pressable API is a tool for our customers to create personalized experiences and automate routine tasks.
  termsOfService: https://pressable.com/legal/
  contact:
    email: help@pressable.com
servers:
- url: https://my.pressable.com/v1
tags:
- name: HTTP
paths:
  /http://localhost:3001//sites/{site_id}/apm/url:
    get:
      tags:
      - HTTP
      summary: Get APM URL
      description: Get the Application Performance Monitoring trace URL for a site
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: We could not locate the requested resources.
                  errors:
                    type: array
                    items:
                      type: string
                    example:
                    - No APM traces available for this site
      operationId: getHttp:Localhost:3001SitesBySiteIdApmUrl
      x-operation-id-source: derived
externalDocs:
  description: Find out more about The Pressable REST based API
  url: https://my.pressable.com/documentation/api/v1
